module.exports = {
  CONNECT: 'connect',
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  CHAT_NEW_CONNECTION: 'chat new connection',
  CHAT_NEW_MESSAGE: 'chat new message',
  CHAT_MESSAGE: 'chat message',
  CHAT_NEW_BROADCAST_MESSAGE: 'chat broadcast message',
  CHAT_INFO_MESSAGE: 'chat info message',
  CHAT_JOIN_ROOM: 'chat join room',
  CHAT_USER_JOIN: 'chat user join',
  TEST_COM_ECHO: '#echo',
  TEST_RES_ECHO: '@echo',
  TEST_COM_BELLO: '#bello',
  TEST_RES_BELLO: '@bello',
};
